### ISSUE TITLE
Underscore 1.4.4 suppout

### ISSUE THREAD

**Issue by aqzhyi** [czottmann/sublime-underscorejs-snippets#2]
Hello, friend.

[Underscore](http://underscorejs.org/) is current 1.4.4.

Would you like to updating to 1.4.4?

![image](https://f.cloud.github.com/assets/1500206/502291/34ea1560-bcac-11e2-8cc1-ac86294951fe.png)

**Comment by czottmann** [comment]
Closed after merging pull requests #3 and #4.
